inertial_frame_id: world
waypoints:
  -
    point: [-48 , -12, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-44 , -8, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-37 , -1, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-35 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-25 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-15 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-5 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [0 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [5 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [15 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [25 , 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [39, 0, -16]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False

